package mcp.mobius.opis.swing;

public enum SelectedTab {
    AMOUNTENTS,
    AMOUNTTES,
    DIMENSIONS,
    PACKETS,
    PLAYERS,
    RENDERENTITIES,
    RENDERTILEENTS,
    SUMMARY,
    TIMINGCHUNKS,
    TIMINGENTITES,
    TIMINGENTITESPERCLASS,
    TIMINGHANDLERS,
    TIMINGTILEENTS,
    TIMINGTILEENTSPERCLASS,
    TIMINGEVENTS,
    PACKETINBOUND,
    PACKETOUTBOUND,
    PACKETINBOUND250,
    PACKETOUTBOUND250,
    ORPHANTES,
    RENDERHANDLERS,
    CLIENTEVENTS,
    THREADS,
    ANY,
    NONE;
}
